[tool.poetry]
name = "rs_9_evaluation_selection"
version = "0.1.0"
description = ""
authors = ["Uladzislau Sakalou"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
